version: '2'

services:
    www:
        container_name: www
        image: nimmis/alpine:latest
        volumes:
            # mount code folder
            - ~/public_html:/data/www
        restart: always
        
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "8080:80"
        links:
            - "php56:php"
        volumes:
            # Custom vhost
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            # nginx log
            - ./log/nginx:/var/log/nginx
        volumes_from:
            - www
        restart: always

        # command: [nginx-debug, '-g', 'daemon off;']
        
    php71:
        container_name: php71
        build: ./image/php/7.1
        volumes:
            - ./config/php/7.1/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            # - ./log/php/7.1:/var/log/php
        volumes_from:
            - www
        links:
            - redis 
            - mysql 
            # - dockerhost 
        restart: always

    php56:
        container_name: php56
        build: ./image/php/5.6
        volumes:
            - ./config/php/5.6/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            # - ./config/php/5.6/php-fpm.d/custom.ini:/usr/local/etc/php-fpm.d/custom.ini
            # - ./log/php/5.6:/var/log/php
        volumes_from:
            - www
        links:
            - redis 
            - mysql 
            # - dockerhost 
        restart: always

    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
            - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        restart: always

    mysql:
        container_name: mysql
        image: leafney/docker-alpine-mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PWD: 'root'
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports: 
            - "8081:80"

    # dockerhost:
    #     container_name: dockerhost
    #     restart: on-failure
    #     image: qoomon/docker-host
    #     cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    #     mem_limit: 4M